### PR TITLE
Merge latest changes from Lincomatic V8.2.1 > V8.2.3

### PR DESCRIPTION
**Pull request by glynhudson**
- PP_AUTO_AMPACITY changes 
- https://github.com/lincomatic/open_evse/issues/156
  -> used to change current capacity to PP ampacity. now, only change it
	if currently higher than PP ampacity
  -> GetMaxCurrentCapacity() is limited to PP ampacity in STATE B/C
	
20230206 SCL
- added BOOTLOCK - when defined, EVSE locked until receives $SB 
- https://github.com/lincomatic/open_evse/issues/154
- Requires WiFi FW V4.2.1 or higher 

20220408 V8.2.1 SCL
- fix bug: SaveSettings() should save GetMaxCurrentCapacity() instead of GetCurrentCapacity(), in case called during throttling

### CODE REVIEW

**Comment by glynhudson** [comment]
@jeremypoulter please could you help with merging these latest changes from Lincomatic. Should this PR be targeting stable? The version numbers are out of sync hence the need to release this under V8.2.3 

@kipk could you advise what build flags features we can now disable since these features are handled in UI V2 e.g energy countes, limits etc

**Comment by KipK** [comment]
I'm not home for few days , but needs something like PP_AUTOAMPACITY ( as before ) for eu builds and BOOTLOCK for all builds ( needs wifi fw > 4.1.7 )

**Comment by lincomatic** [comment]
I cannot change the platformio.ini to fit users' specific needs. Sorry. OpenEVSE needs to use their own platformio.ini

**Comment by KipK** [comment]
That's already the case on openEvse git. Those flags should be added there.

**Comment by jeremypoulter** [comment]
@glynhudson Looks good to me, both repos now use `master` as the main/stable branch now. This means GitHub tracks the differences between the two repos better

**Comment by KipK** [comment]
@glynhudson , I don't have it under my eyes now but  the flags we can disable are the one for limits and timers. I would keep energy meter even if handled by ESP32 now and remove it later ( needs to keep the amp sampling but remove the counter part ) .
I think RAPI_WF can be disabled too and perhaps some other older stuff.

**Comment by KipK** [comment]
so here are my compile flags here : 

`build_flags =
  -D OEV6
  -D RELAY_PWM
  -D SHOW_DISABLED_TESTS
  -D AMMETER
  -D RAPI
  -D RAPI_SERIAL
  #-D RAPI_WF
  -D RAPI_BTN
  #-D TIME_LIMIT
  #-D CHARGE_LIMIT
  -D MENNEKES_LOCK
  -D DELAYTIMER
  -D RTC 
  -D BOOTLOCK`

And no change for the emonevse but only need one now, no threephase needed:
```

[env:emonevse]
extends = env:openevse
build_src_flags=
  ${common.eu_build_flags}
  -D PP_AUTO_AMPACITY
  -D 'VERSION="${common.version}.T2"'
```

BOOTLOCK enabled will need to mention this firmwarze needs next release wifi fw version ( 4.1.7 won't unlock the evse )

**Comment by KipK** [comment]
I've remade the PR with solved conflicts #19

**Pull request closed without merging**
